In [2]:
import numpy as np

In [2]:
def get_problem_1():
    process_200 = np.random.randint(10, 1001, 200)
    process_100 = np.random.randint(100, 301, 100)
    processing = np.zeros(300)
    processing[:200] = process_200
    processing[200:] = process_100
    return processing

def get_problem_2():
    process_150_1 = np.random.randint(10, 1001, 150)
    process_150_2 = np.random.randint(400, 701, 150)
    processing = np.zeros(300)
    processing[:200] = process_150_1
    processing[200:] = process_150_2
    return processing

def get_problem_3():
    processing = [50, 50, 50]
    for i in range(100 - 51):
        processing.append(i + 51)
        processing.append(i + 51)
    return processing

In [60]:
class Initializer():
    def __init__(self, num_jobs, num_machines, population_size):
        self.num_jobs = num_jobs
        self.num_machines = num_machines
        self.population_size = population_size
    def random(self):
        init = np.zeros((self.num_jobs, self.population_size))
        for i in range(self.population_size):
            init[i] = np.random.randint(1, self.num_machines + 1, self.num_jobs)
        return init
    def equal_distribution(self):
        per_machine = self.num_jobs // self.num_machines
        init = []
        for i in range(self.num_machines):
            init.append([i+1] * per_machine)
        init = np.ravel(np.asarray(init))
        if len(init) != self.num_jobs:
            for i in range(self.num_jobs - len(init)):
                init = np.append(init, 1)
        return init

In [61]:
i = Initializer(10,5,10)
print(i.random())

[[2. 2. 2. 3. 2. 1. 2. 1. 2. 3.]
 [4. 4. 3. 2. 1. 1. 2. 3. 2. 3.]
 [1. 2. 2. 3. 5. 4. 3. 2. 4. 2.]
 [1. 4. 5. 3. 1. 5. 1. 4. 4. 4.]
 [1. 5. 3. 1. 5. 4. 3. 3. 3. 4.]
 [4. 4. 5. 5. 5. 4. 1. 5. 1. 4.]
 [5. 4. 3. 5. 3. 5. 4. 2. 1. 4.]
 [2. 5. 4. 3. 5. 2. 5. 4. 4. 3.]
 [3. 5. 2. 3. 4. 1. 5. 2. 2. 5.]
 [2. 2. 1. 3. 4. 3. 3. 1. 3. 4.]]


In [56]:
class Selector():
    def roulette(self):
        raise NotImplementedError
    def tournament(self, candidates):
        return max(candidates)

In [101]:
class Recombiner():
    def __init__(self, chromosomes):
        self.chromosomes = chromosomes
        self.crossover_probability = .5
        
    def crossover_random_num(self):
        return np.random.random()
    
    def get_random_pair(self):
        pair = np.random.randint(0, len(self.chromosomes), 2)
        while pair[0] == pair[1]:
            pair[1] = np.random.randint(0, len(self.chromosomes))
        return pair
    
    def one_point_crossover(self):
        pair = self.get_random_pair()
        mom = self.chromosomes[pair[0]]
        dad = self.chromosomes[pair[1]]
        print(mom)
        print(dad)
        cross_chance = self.crossover_random_num()
        print(cross_chance, "<", self.crossover_probability)
        if cross_chance < self.crossover_probability:
            crossover_point = np.random.randint(1, len(self.chromosomes))
            child1, child2 = [], []
            from_mom = True
            for i in range(len(self.chromosomes)):
                if i == crossover_point:
                    from_mom = False
                if from_mom:
                    child1.append(mom[i])
                    child2.append(dad[i])
                else:
                    child1.append(dad[i])
                    child2.append(mom[i])
            return child1, child2
        else:
            return mom, dad
        
    def two_point_crossover(self):
        pair = self.get_random_pair()
        mom = self.chromosomes[pair[0]]
        dad = self.chromosomes[pair[1]]
        cross_chance = self.crossover_random_num()
        if cross_chance < self.crossover_probability:
            crossover_point1 = np.random.randint(1, len(self.chromosomes[1]))
            crossover_point2 = np.random.randint(1, len(self.chromosomes[1]))
            while crossover_point1 == crossover_point2:  # make sure they are not the same
                crossover_point2 = np.random.randint(1, len(self.chromosomes))
            child1, child2 = [], []
            from_mom = True
            for i in range(len(self.chromosomes)):
                if i == crossover_point1:
                    from_mom = False
                if i == crossover_point2:
                    from_mom = True
                if from_mom:
                    child1.append(mom[i])
                    child2.append(dad[i])
                else:
                    child1.append(dad[i])
                    child2.append(mom[i])
            return child1, child2
        else:
            return mom, dad

In [102]:
r = Recombiner(np.array([[0,0,0,0],[1,1,1,1]]))

In [103]:
r.one_point_crossover()

[0 0 0 0]
[1 1 1 1]
0.10749004284530128 < 0.5


([0, 1], [1, 0])

In [104]:
test = np.array([[0,0,0,0],[1,1,1,1]])

In [105]:
len(test)

2

In [106]:
len(test[1])

4