In [6]:
import numpy as np
import matplotlib.pyplot as plt
import itertools

In [7]:
def swap(entry):
    neighbors = []
    neighbor = []
    mod = len(entry)
    
    for i in range(len(entry)):
        last = i + 1
        if i == mod - 1:
            last = 0
        neighbor = entry.copy()
        neighbor[last], neighbor[i] = entry[i], entry[last]
        neighbors.append(neighbor)
    return neighbors

In [8]:
def transposition(entry):
    neighbors = list(itertools.permutations(entry))
    neighbors.pop(0)
    return neighbors

In [9]:
class Knapsack:
    def __init__(self, num_items, max_weight=400):
        self.max_weight = max_weight
        self.values = self.get_values(num_items)
        self.select = [0] * num_items
        self.weights = self.get_weights(num_items)
        
    def get_values(self, num):
        return np.random.randint(1, high=1000, size=num)
    
    def get_weights(self, num):
        return np.random.randint(1, high=self.max_weight, size=num)
    
    def randomize_select(self):
        self.select = np.random.randint(0, 2, size=len(self.select))

In [19]:
def get_total_value(vals, selections):
    value = []
    for i in range(len(vals)):
        if selections[i] == 1:
            value.append(vals[i])
    return np.sum(value)

def check_weight_compatability(weights, selections, maxi):
    weight = []
    for i in range(len(weights)):
        if selections[i] == 1:
            weight.append(weights[i])
    total_weight = np.sum(weight)
    return 1 if total_weight < maxi else 0

def first_choice_hill_climb(sack, neighbor_type):
    weight_pass = 0
    while weight_pass == 0:
        weight_pass = check_weight_compatability(sack.weights, sack.select, sack.max_weight)
        if weight_pass == 0:
            print("Initial selection is invalid: Max weight exceeded!  Reseeding...")
            sack.randomize_select()
    print("SUCCESS")
    first_val = get_total_value(sack.values, sack.select)
    if neighbor_type == 'swap':
        new_vals = []
        new = swap(sack.select)
        for n in new:
            new_vals.append(get_total_value(sack.values, n))
        if max(new_vals) < first_val:
            return sack.select
        else:
            first_val = max(new_vals)
            sack.select = new_vals[np.argmax(new_vals)]
        
def hill_climb(sack, neighbor_type):
    if neighbor_type == 'swap':
        

In [28]:
sack = Knapsack(5)
print(sack.values)
print(sack.weights)
sack.randomize_select()
print(sack.select)

[ 19 529  57 583 979]
[371 154 360 204 370]
[1 1 1 0 0]


In [29]:
first_choice_hill_climb(sack, 'swap')

Initial selection is invalid: Max weight exceeded!  Reseeding...
Initial selection is invalid: Max weight exceeded!  Reseeding...
Initial selection is invalid: Max weight exceeded!  Reseeding...
Initial selection is invalid: Max weight exceeded!  Reseeding...
Initial selection is invalid: Max weight exceeded!  Reseeding...
SUCCESS
